### ISSUE TITLE
setup报错找不到文件

### ISSUE THREAD

**Issue by Reyipcy** [FuryMartin/Picf#13]
setup一直报错说找不到文件 不知道是我打开方式不对？

**Comment by Reyipcy** [comment]
ModuleNotFoundError: No module named 'brute_force_cython_ext' 救

**Comment by FuryMartin** [comment]
你的报错是这样的吗？
```bash
(Picf) ~/Picf >>> python main.py                                                                                                                   
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    from gui.uis.windows.main_window.functions_main_window import *
  File "/home/fury/Picf/gui/uis/windows/main_window/__init__.py", line 19, in <module>
    from . ui_main import UI_MainWindow
  File "/home/fury/Picf/gui/uis/windows/main_window/ui_main.py", line 40, in <module>
    from . setup_main_window import *
  File "/home/fury/Picf/gui/uis/windows/main_window/setup_main_window.py", line 24, in <module>
    from utils.face_functions import get_duplicate_pics, search_person_pics, sorter_main
  File "/home/fury/Picf/utils/face_functions.py", line 13, in <module>
    from imagededup.methods import PHash
  File "/home/fury/Picf/imagededup/methods/__init__.py", line 1, in <module>
    from .hashing import PHash, AHash, DHash, WHash
  File "/home/fury/Picf/imagededup/methods/hashing.py", line 10, in <module>
    from imagededup.handlers.search.retrieval import HashEval
  File "/home/fury/Picf/imagededup/handlers/search/retrieval.py", line 9, in <module>
    from imagededup.handlers.search.brute_force_cython import BruteForceCython
  File "/home/fury/Picf/imagededup/handlers/search/brute_force_cython.py", line 3, in <module>
    import brute_force_cython_ext
ModuleNotFoundError: No module named 'brute_force_cython_ext'
```
如果是，说明没有完成imagededup的setup。请执行下列代码：
```bash
(Picf) ~/Picf >>> cd imagededup                                                                                                                 [1]
(Picf) ~/Picf/imagededup >>> python setup.py install   
```
