### ISSUE TITLE
选取文件夹后运行出错   请问是图片的原因吗  我用的是ORL数据集中pgm图片转为的jpg

### ISSUE THREAD

**Issue by lanshan9825** [FuryMartin/Picf#17]
您好，我下载运行后出现了以下错误，搜索之后并没有找到解决方法
能麻烦您看一下吗
Microsoft Windows [版本 10.0.22621.1413]
(c) Microsoft Corporation。保留所有权利。

E:\Picf_v1.6>conda activate Picf
(Picf) E:\Picf_v1.6>python main.py

Started 3 processes..
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Code\Anaconda3\envs\Picf\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\Code\Anaconda3\envs\Picf\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "E:\Picf_v1.6\utils\embedder.py", line 71, in save_embeddings
    model = load_model("Models/facenet.h5",compile=False)
  File "D:\Code\Anaconda3\envs\Picf\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\Code\Anaconda3\envs\Picf\lib\site-packages\keras\utils\generic_utils.py", line 792, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Picf_v1.6\gui\uis\windows\main_window\setup_main_window.py", line 460, in run
    sorter_main(self.path)
  File "E:\Picf_v1.6\utils\face_functions.py", line 17, in sorter_main
    if embedder(image_paths):
  File "E:\Picf_v1.6\utils\embedder.py", line 182, in embedder
    pool.map(partial_embeddings, split_data)
  File "D:\Code\Anaconda3\envs\Picf\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\Code\Anaconda3\envs\Picf\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
ValueError: bad marshal data (unknown type code)

**Comment by FuryMartin** [comment]
根据你提供的错误信息，参见 [keras ValueError: bad marshal data (unknown type code)](https://stackoverflow.com/questions/70329055/keras-valueerror-bad-marshal-data-unknown-type-code)，怀疑可能是Python版本和TF版本较高导致的。

请检查你所使用的依赖包的版本，发布时的测试环境使用的依赖包可以在 [resources/environment.yml](https://github.com/FuryMartin/Picf/blob/master/resources/environment.yml) 查看到

**Comment by lanshan9825** [comment]
> 

谢谢回复。确实是python版本的问题。不知道为何用脚本创建的环境python版本却与脚本中写的3.8.5不同，但改为3.8.5之后已经可以正常运行。顺便感谢分享项目！
